[package]
name = "jma-rap"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
time = { version = "0.3", features = ["macros"] }

[dev-dependencies]
anyhow = "1.0.80"
time = { version = "0.3", features = ["macros", "formatting"] }
